apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: model-server-test1-gitops
  description: This is GitOps manifest for model-server-test1   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:
    # ArgoCD apps from this template used rhtap-gitops as the grouping
    argocd/app-selector: rhtap/gitops=model-server-test1
    janus-idp.io/tekton: model-server-test1 
    backstage.io/kubernetes-id: model-server-test1 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:default/tpetkos 
  lifecycle: experimental  
