apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  argocd/app-name: model-server-test1
  janus-idp.io/tekton: model-server-test1
  backstage.io/kubernetes-id: model-server-test1
  backstage.io/kubernetes-namespace: rhdh-app
  app.kubernetes.io/part-of: model-server-test1
resources:
  - initialize-namespace/
  - pvc.yaml
  - deployment-model-server.yaml
  - service-model-server.yaml
  - model-config.yaml
