apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/instance: model-server-test1
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: model-server-test1
  name: model-server-test1
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi
